"""initial Migrate

Revision ID: 0e08f2dfa86a
Revises: 
Create Date: 2024-10-03 19:54:18.923074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e08f2dfa86a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "films",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column(
            "age_rating",
            sa.Enum("G", "PG", "PG_13", "R", "NC_17", "TV_MA", name="agerating"),
            nullable=False,
        ),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("release_year", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("hashed_password", sa.String(length=512), nullable=False),
        sa.Column("role", sa.Enum("USER", "CASHIER", name="role"), nullable=False),
        sa.Column("full_name", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "film_genre",
        sa.Column("film_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["film_id"],
            ["films.id"],
        ),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
        ),
        sa.PrimaryKeyConstraint("film_id", "genre_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("film_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["film_id"],
            ["films.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("basic_price", sa.Numeric(), nullable=False),
        sa.Column(
            "room_number",
            sa.Enum(
                "ROOM_1",
                "ROOM_2",
                "ROOM_3",
                "ROOM_4",
                "ROOM_5",
                "ROOM_6",
                "ROOM_7",
                "ROOM_8",
                "ROOM_9",
                name="roomnumber",
            ),
            nullable=False,
        ),
        sa.Column(
            "row_number",
            sa.Enum(
                "ROW_1", "ROW_2", "ROW_3", "ROW_4", "ROW_5", "ROW_7", name="ticketrow"
            ),
            nullable=False,
        ),
        sa.Column(
            "place",
            sa.Enum(
                "PLACE_1",
                "PLACE_2",
                "PLACE_3",
                "PLACE_4",
                "PLACE_5",
                "PLACE_6",
                "PLACE_7",
                "PLACE_8",
                "PLACE_9",
                "PLACE_10",
                name="place",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tickets")
    op.drop_table("tokens")
    op.drop_table("sessions")
    op.drop_table("film_genre")
    op.drop_table("users")
    op.drop_table("genres")
    op.drop_table("films")
    # ### end Alembic commands ###
