"""Add Film

Revision ID: 92c655aa3b35
Revises: 633094cf9d4c
Create Date: 2024-10-03 13:46:35.074389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c655aa3b35'
down_revision: Union[str, None] = '633094cf9d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('age_rating', sa.Enum('G', 'PG', 'PG_13', 'R', 'NC_17', 'TV_MA', name='agerating'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Enum('ACTION', 'COMEDY', 'DRAMA', 'HORROR', 'FANTASY', 'SCI_FI', 'ROMANCE', 'THRILLER', 'DOCUMENTARY', 'ANIMATION', 'MYSTERY', 'ADVENTURE', 'FAMILY', 'CRIME', 'MUSICAL', 'HISTORICAL', name='genre'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('film_genre',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_genre')
    op.drop_table('genres')
    op.drop_table('films')
    # ### end Alembic commands ###
