"""Rename Session.film on film_id

Revision ID: f0d9d2e2d2a8
Revises: f351d884a203
Create Date: 2024-10-03 16:36:37.633038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d9d2e2d2a8'
down_revision: Union[str, None] = 'f351d884a203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('film_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sessions', 'films', ['film_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'film_id')
    # ### end Alembic commands ###
