"""Gener Association Update

Revision ID: 3d06be4ddfc6
Revises: 625e0ad78180
Create Date: 2024-10-03 14:08:16.624272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d06be4ddfc6'
down_revision: Union[str, None] = '625e0ad78180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
